const About = () => {
  return (
    <div className="my-3">
      <h1 className="text-center my-5">About Todo App</h1>
      <p>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aliquam est mauris. Pellentesque venenatis at lacus at tristique. Aliquam ipsum dolor, lobortis nec ultrices quis, tempus nec dui. Integer pharetra sem quis ipsum dictum, sit amet semper enim euismod. Etiam faucibus risus quis diam iaculis, non viverra elit ullamcorper. Cras dapibus tellus ut nulla tincidunt, a vulputate tellus venenatis. Donec vehicula quam non enim gravida, nec lacinia nulla vestibulum. Duis eu porttitor ante. Pellentesque lacinia massa a dolor fringilla consequat. Aenean rhoncus tempus augue. Donec sagittis, justo id pellentesque consequat, nisi nibh tempor erat, eu vehicula nibh sem non lacus. Sed quis lorem felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque erat arcu, vulputate ac nisi semper, porta mattis erat. Phasellus eget odio quis magna tincidunt ultricies vitae at quam. Phasellus ligula purus, suscipit vel tempus eu, eleifend non mauris. Maecenas sapien libero, consequat et tellus sed, convallis tempor libero. Mauris pharetra mi quis finibus interdum. Quisque sit amet pellentesque nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Cras eu diam suscipit, posuere diam id, bibendum metus. Aliquam tincidunt efficitur leo. Nullam a pretium magna. Curabitur eleifend in mi in mattis. In vel eros dignissim, rhoncus neque a, ornare massa. Suspendisse elementum mauris blandit felis convallis varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin sed velit sed ex efficitur ornare nec et nibh.

Fusce tincidunt pellentesque justo, vitae molestie elit. Pellentesque eu orci enim. Nam pulvinar urna vel lectus pellentesque maximus. Pellentesque consequat enim vel odio laoreet porta. Praesent ante urna, varius in ipsum non, semper molestie dolor. Donec et varius tortor. Ut sed nibh diam. Vestibulum vel quam a felis sodales condimentum. Sed lobortis ipsum vel malesuada convallis. Pellentesque ex est, egestas at feugiat sed, fringilla ac neque. Morbi vestibulum hendrerit consequat. Curabitur a accumsan eros. Pellentesque vestibulum pharetra pulvinar. Nunc auctor leo facilisis felis convallis consectetur. Sed at felis nec augue viverra tempus. Sed mattis vitae ex ac bibendum.

Nullam eu efficitur nunc. Sed tempor massa vel feugiat tempus. Morbi et tincidunt eros. Vestibulum at velit quis urna vehicula maximus. In sapien libero, tempus ac ante ut, consectetur pulvinar lorem. Proin sollicitudin enim risus, non tempor eros luctus non. Nam aliquet nulla interdum tortor commodo mollis. Aenean blandit leo sit amet erat pharetra, ultrices rhoncus tellus fringilla. Nulla convallis porta elit quis aliquet. Mauris maximus est ligula, sed egestas diam semper ac. Curabitur vitae facilisis lorem. Nulla at magna suscipit, dignissim libero sed, maximus eros. Suspendisse potenti. Mauris eget dui arcu.

Mauris nunc justo, sollicitudin quis ligula ac, aliquet lacinia justo. Maecenas turpis libero, euismod sed malesuada quis, laoreet sit amet ligula. Sed vel augue augue. Maecenas fermentum aliquam metus ac condimentum. Ut eleifend est in faucibus interdum. Duis rutrum tortor id tempus interdum. Suspendisse magna urna, sollicitudin eget porta vitae, pretium sit amet justo. Nam auctor tincidunt tortor vel condimentum. Etiam vehicula leo sed nibh egestas, in dignissim dui hendrerit. Praesent volutpat, dolor faucibus porta vulputate, nisl odio porta turpis, ac elementum metus purus at nisl. Phasellus eget lorem nec ipsum pulvinar iaculis. Suspendisse a tellus mauris. Vivamus lobortis, tellus in laoreet laoreet, nulla urna aliquam odio, nec pharetra dui magna ullamcorper ligula. Quisque eget ipsum et metus dictum bibendum. Integer sit amet erat interdum, aliquam arcu a, mattis diam. Suspendisse potenti.

Donec ac sapien sit amet odio commodo vehicula. In tincidunt finibus hendrerit. Suspendisse potenti. Suspendisse potenti. Cras eu odio in quam rutrum dignissim vitae nec nibh. Vivamus tristique mi id dui interdum fringilla. Nunc vitae sodales felis, vitae tristique arcu. Phasellus dictum turpis nec nisl aliquam interdum convallis in ante. Quisque elit enim, maximus vitae dui vitae, feugiat blandit elit. Vivamus vulputate ut ex efficitur hendrerit. In tempor sapien ac justo feugiat, eget faucibus eros venenatis.

Suspendisse in nunc orci. Curabitur et dolor libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed euismod tortor eu luctus ultricies. Praesent vel imperdiet sem. Nulla quis nibh nec augue fermentum tincidunt at vel arcu. Nunc in faucibus augue. In hac habitasse platea dictumst.

Mauris convallis hendrerit interdum. Etiam venenatis sollicitudin consectetur. Pellentesque venenatis elit sit amet lorem venenatis, eu placerat urna sollicitudin. Cras pellentesque felis non nisl elementum, sit amet aliquet lorem sagittis. Praesent molestie mattis ipsum, volutpat facilisis quam fermentum vitae. Nam gravida ex pellentesque, pulvinar odio eget, efficitur lectus. Aenean efficitur ligula erat, sed volutpat sapien lacinia at. Suspendisse sed eros enim. Nunc ut nibh nec sapien sollicitudin sollicitudin non et ante. Vestibulum mattis bibendum arcu, quis commodo sem interdum at. Nam iaculis ipsum ac nunc tincidunt, eu consequat nisi ullamcorper.

Proin egestas sodales turpis. Sed ornare neque elementum placerat rutrum. Aliquam in dui sed elit finibus commodo euismod quis lectus. Ut sollicitudin sem ut odio lobortis ullamcorper. In hac habitasse platea dictumst. Nulla elementum ut massa id commodo. Sed maximus elementum enim quis accumsan. Nunc vitae tellus sed sem tempor porta. Maecenas interdum quam id mollis gravida. Suspendisse potenti. Nunc neque lectus, scelerisque quis dignissim ac, aliquam ac arcu. Sed fringilla tortor sed faucibus tincidunt. Nulla vitae dictum libero, in vulputate urna.

Phasellus tempus tristique elit, sit amet scelerisque purus tincidunt vel. Ut finibus nunc id libero blandit, et cursus velit ullamcorper. Quisque maximus congue imperdiet. Sed accumsan sagittis felis, at eleifend purus lacinia sit amet. Vivamus a enim consectetur, ullamcorper eros et, semper mauris. Etiam ornare sollicitudin orci, eu cursus enim ultricies id. Aenean sed magna semper, accumsan tellus lobortis, scelerisque ipsum. Vivamus molestie nibh id lacus fermentum, vel blandit mauris tincidunt. Aliquam mattis massa tellus, et elementum lectus porta vitae. Cras faucibus finibus diam, cursus ultricies purus viverra semper.

Donec elementum lacus vitae metus facilisis ullamcorper. Nullam condimentum urna eget ipsum feugiat, eget ullamcorper quam facilisis. Nullam viverra metus eget turpis vestibulum, ut egestas lacus pharetra. Mauris luctus leo non vulputate luctus. Nulla facilisi. Donec id leo a urna bibendum rutrum eu vitae eros. Praesent mattis felis sed scelerisque lacinia.

Nam placerat, ipsum quis pulvinar rutrum, orci leo rutrum elit, at lacinia nunc est vel sem. Aliquam semper efficitur elit, sit amet dictum eros pellentesque nec. Cras at nibh imperdiet, ultrices nibh sit amet, ultrices tellus. Morbi accumsan eu ante eu feugiat. Cras ut erat tincidunt, commodo urna et, interdum erat. Vivamus sed commodo arcu. Proin at dolor eget lectus volutpat semper vitae in ligula. Nulla commodo ipsum lectus, sit amet fringilla nisl malesuada commodo.

Sed sed eros sit amet mauris pretium pellentesque. Nullam dui felis, consequat id tempus eget, lobortis in odio. Sed in diam vel lacus iaculis iaculis. Nam sagittis nisi ac sem sodales ullamcorper. Pellentesque eu tellus eu mauris pretium gravida. Aenean laoreet efficitur nunc, non viverra tortor venenatis vel. Vestibulum sodales egestas est sed molestie. Mauris vel iaculis nulla. Pellentesque nec magna nulla. Ut ultrices auctor tortor, ullamcorper malesuada leo suscipit ut. Suspendisse potenti. Sed dictum est dolor, ac luctus nisl iaculis a. Mauris porta mauris vel nibh bibendum, non faucibus ex pulvinar. Donec ullamcorper sodales lorem non pretium. Duis id volutpat mauris.

Morbi finibus ipsum sed elit mattis auctor. Morbi at volutpat turpis. Aenean lacus justo, blandit a ultrices vel, convallis ut ante. Cras tempus odio eget est posuere sollicitudin. Praesent quis tincidunt tellus. Nam tristique, mauris sed tincidunt auctor, lectus sem viverra ex, at eleifend enim ante sit amet lacus. Curabitur ac interdum mi, at gravida purus. Fusce sed leo eu turpis eleifend tristique. Suspendisse egestas sit amet ligula eget ultricies. Praesent a neque nibh. Sed lacinia massa sit amet semper viverra. Quisque mollis mattis hendrerit. Ut aliquam, nisi a iaculis egestas, mi sapien ultrices neque, in tempor nibh mi sed tortor. Nullam consectetur sollicitudin congue. Pellentesque consequat a ligula ac euismod. Vestibulum et cursus urna.

Ut turpis ligula, auctor sit amet libero non, pharetra pharetra nisi. Donec ante velit, molestie sit amet sapien sit amet, varius rutrum tellus. Maecenas placerat posuere nibh et fringilla. Integer scelerisque, massa nec mattis commodo, ex lorem pellentesque elit, vitae vehicula est justo ullamcorper risus. Aenean finibus ligula est, et auctor tortor efficitur nec. Nullam euismod nulla risus, vel ornare magna mattis non. Praesent commodo fringilla lectus, quis consectetur nulla lacinia ac. Mauris feugiat, tellus id hendrerit luctus, mi lorem laoreet erat, at vulputate ex elit vel risus. Pellentesque nec erat eu erat congue porttitor. Nam at ipsum sed arcu laoreet accumsan. Proin nisi augue, maximus eu sodales ut, mattis id justo. Duis scelerisque pharetra condimentum. Nullam viverra pellentesque elementum. Vivamus felis metus, maximus at lectus sed, aliquam interdum ex. Curabitur id nisi vitae libero ultrices consectetur sollicitudin id augue. Vestibulum et ultricies neque.

In et orci vel justo venenatis molestie sodales et eros. Sed in massa eget risus venenatis elementum eu ut urna. Suspendisse potenti. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In nec congue nulla. Vivamus et efficitur nisl, at viverra nibh. Proin nec metus sed eros facilisis cursus interdum eget urna. Aliquam arcu turpis, consequat non molestie ut, finibus non erat. Suspendisse potenti. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vitae nisi sed magna tincidunt molestie eu id odio. Maecenas vel tortor consectetur, venenatis dolor in, porttitor libero. Phasellus viverra sollicitudin turpis, feugiat commodo tortor eleifend quis.

Pellentesque ante mauris, viverra at nunc ac, porta feugiat est. Praesent blandit diam diam, a luctus risus tincidunt a. Quisque semper finibus hendrerit. Praesent id nisi elit. Donec vitae ligula id dui ultrices dictum. Etiam in nisi eu nibh viverra porttitor. Nam lacinia felis a pellentesque viverra. Ut in rutrum enim, vel imperdiet nulla. Praesent aliquet justo a fringilla fermentum. Vestibulum non mattis eros, vitae egestas libero.

Vivamus ut tellus et tortor dignissim cursus id ac diam. Integer varius condimentum dui rutrum placerat. Donec tincidunt felis volutpat, rutrum dolor vitae, tempor diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum nec quam eget nisi tincidunt condimentum eu at massa. Etiam sit amet massa vitae lacus tincidunt tristique. Donec ut lacus quis erat cursus interdum. Sed hendrerit, quam eget dapibus suscipit, ipsum lacus blandit urna, a mollis enim arcu vel orci. Integer ac lorem hendrerit, lacinia erat vel, bibendum urna. Etiam congue, mauris non dignissim lobortis, metus leo dictum lectus, ut suscipit sapien massa ac ligula. Maecenas aliquet sed purus quis malesuada. In imperdiet ligula augue, non euismod neque cursus quis. Vivamus ipsum ex, molestie a leo eu, bibendum mollis ligula. Mauris ligula nulla, suscipit sit amet mauris sit amet, laoreet hendrerit orci. Sed facilisis faucibus nulla vel convallis.

Aenean vitae velit quis erat lobortis egestas nec feugiat velit. Duis semper egestas ligula, eget pulvinar arcu. Donec eleifend imperdiet metus eget tristique. Praesent feugiat, diam vel mollis hendrerit, diam erat vulputate dolor, vitae egestas mi nibh in diam. In luctus non neque id pharetra. Sed blandit sed nulla eu congue. Sed posuere, ante vel ultricies suscipit, dui tellus fermentum lacus, et ullamcorper sem ipsum nec sem. Donec suscipit est vel commodo elementum. Quisque lectus eros, molestie sit amet elit et, tristique elementum sapien.

Nunc consequat laoreet tellus dapibus imperdiet. Morbi bibendum turpis ut tortor eleifend viverra. Praesent dignissim sed odio dapibus auctor. Sed interdum sem id erat tincidunt ullamcorper eget non dui. Nunc sagittis ornare neque, eget varius tellus ultricies eget. Vestibulum venenatis efficitur ex in ornare. Curabitur a gravida orci. Sed egestas non quam id iaculis. Etiam tincidunt, velit id lobortis eleifend, libero neque vulputate lacus, molestie tempus felis lectus vel libero. Ut ut lorem in orci viverra blandit non vitae lectus. Nulla commodo nulla sed elit tristique scelerisque. Vestibulum ut aliquam leo. Nullam justo dolor, facilisis eu porta id, fermentum in lacus. Etiam rutrum porta facilisis.

Nullam in nisi non tortor fermentum elementum nec nec mi. Sed imperdiet sem odio, sed aliquam urna semper nec. Suspendisse nisi mauris, posuere ut risus in, varius fringilla mi. In cursus eleifend hendrerit. Proin in eros quam. Mauris tristique, odio nec elementum molestie, dui odio vulputate ante, sit amet aliquam arcu ex sit amet eros. Suspendisse nisl enim, finibus in massa sed, convallis consectetur nibh. Integer luctus suscipit erat vel lobortis. Quisque sapien felis, imperdiet a nulla vitae, efficitur sollicitudin velit. Pellentesque nunc augue, feugiat at varius quis, porta ac mi. Mauris mollis gravida orci, ut ultrices mauris tempor sed. Integer at commodo erat. Integer interdum sapien nec nibh tristique tincidunt.

Pellentesque dui nunc, molestie ut mi eget, vehicula eleifend massa. Donec sit amet malesuada felis. Integer aliquam nisi nisi, a facilisis neque venenatis vel. Cras tincidunt nulla sed vulputate ultrices. Vestibulum dignissim ipsum nec nisi efficitur, tempor venenatis tortor aliquet. Nulla luctus pulvinar risus, eu tempor risus sagittis ut. Phasellus nec efficitur nulla. Suspendisse quis diam ipsum. Praesent eget lacus interdum, efficitur dolor nec, ullamcorper enim. Maecenas vel ornare lectus. Etiam ut ornare quam, eu vehicula lorem.

Suspendisse potenti. Etiam et feugiat elit. Nam nec purus rhoncus, pretium nisi id, luctus orci. Duis id sodales enim. Duis placerat orci mollis, tempor lacus nec, fermentum neque. Ut elementum convallis mauris, a vulputate nibh lacinia ut. Pellentesque tristique nisi massa, sit amet ultrices tellus tincidunt in. Nulla semper vehicula bibendum. Duis sit amet orci vel odio ultrices facilisis eu vel quam. Phasellus sit amet augue dapibus, lobortis magna vel, iaculis lectus. Vestibulum neque diam, luctus vel fermentum id, vehicula nec orci.

Maecenas sit amet imperdiet erat, nec ullamcorper orci. Proin diam lorem, varius eu purus tempus, efficitur lobortis risus. Pellentesque non auctor leo. Mauris eget ultrices odio. Donec eu tempor justo. Suspendisse porta dignissim augue, placerat venenatis purus suscipit nec. Aliquam egestas mollis tortor, et porttitor enim ultrices at. Nulla varius diam at sapien sagittis, ut semper massa semper. Morbi eleifend mi ut lacinia pretium.

Nulla vitae mi in dolor rutrum commodo quis id massa. Donec eget lacus non justo imperdiet accumsan non vitae elit. Morbi dapibus eleifend eros eleifend egestas. In sit amet nisl sit amet dui rhoncus fringilla. Fusce in felis et libero consequat iaculis ac vitae justo. Donec convallis erat vel libero dapibus, at semper ligula condimentum. Aliquam convallis elit eu nisl pharetra, eu consectetur augue vestibulum. Curabitur vulputate lectus vel nunc aliquam pellentesque. Quisque sed dolor sit amet lectus molestie pellentesque imperdiet id arcu. Donec posuere in dui et eleifend. Donec in urna vitae neque tincidunt convallis.

Nulla fringilla viverra lacus et rutrum. Aliquam porttitor metus in mi tristique mattis. Etiam ornare tincidunt tincidunt. Aenean in elit vel diam vehicula pretium vel in leo. Donec vel lorem egestas, malesuada metus sed, pretium leo. Maecenas sodales placerat imperdiet. Curabitur vitae augue ipsum. Cras massa justo, placerat vel libero vel, vulputate consectetur erat.

Nullam pharetra gravida magna, eu iaculis leo vulputate ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent varius magna sit amet aliquet placerat. Integer porta varius lacinia. Donec eu nunc sodales, aliquet nulla vitae, accumsan nibh. Praesent sagittis nisi id erat faucibus, eu convallis massa vehicula. Phasellus mauris odio, consectetur id gravida vitae, blandit at arcu. Duis eleifend elit sit amet est laoreet mollis. Praesent blandit condimentum laoreet. Mauris et nulla semper, tristique tellus sodales, mattis dolor. Phasellus tellus tellus, auctor vel facilisis ac, ultricies in ligula. Aenean pellentesque molestie dui eu mollis. Donec eget interdum ex. Sed vel eros luctus, congue purus at, semper massa.

Quisque pellentesque fringilla quam sit amet vehicula. Cras tincidunt augue sed libero cursus, id cursus augue feugiat. Vestibulum dignissim accumsan faucibus. Phasellus volutpat quam ac neque commodo sagittis. Pellentesque turpis mauris, auctor ut erat at, eleifend posuere orci. In ut sollicitudin diam. Nam gravida aliquam ex sed lobortis. Proin bibendum, odio eget auctor dignissim, dui augue iaculis nisi, non vestibulum nibh lorem vel nisl. Integer ultrices arcu ut nisi porttitor, eget laoreet tellus congue. Etiam eget lobortis nisl, ut commodo sem.

Sed placerat dignissim semper. Proin pellentesque massa mi, vel sagittis tellus pretium vitae. Maecenas vitae nulla fermentum, auctor felis ac, bibendum est. Aenean mollis sollicitudin lacus, non dapibus nisi interdum in. Nam ullamcorper vestibulum tellus sed dapibus. Nulla venenatis pellentesque arcu, sed iaculis dolor accumsan porttitor. Morbi molestie lorem nec luctus feugiat. In facilisis ultricies lorem, eget lacinia lorem vestibulum sit amet. Nunc facilisis velit et libero aliquet, id pulvinar dui blandit. Nunc malesuada turpis vitae justo ullamcorper, et imperdiet arcu scelerisque. Nunc tincidunt nibh sed neque euismod, sed rutrum libero ultricies. Nam molestie dolor dolor, fringilla ornare libero gravida ac. Donec ullamcorper ante a erat ornare, vel euismod leo pulvinar.
      </p>
      </div>
  )
}

export default About
